### ISSUE TITLE
Panic when running `deck file openapi2kong`

### ISSUE THREAD

**Issue by imurata** [Kong/deck#1422]
When I run openapi2kong on Ubuntu container, it panics.
```sh
root@apiops:~# deck file openapi2kong -s ./test.yaml --verbose 9
2024/10/21 07:25:57 "level"=2 "msg"="received OpenAPI2Kong options" "options"={"Tags"=[] "DocName"="" "UUIDNamespace"="6ba7b810-9dad-11d1-80b4-00c04fd430c8" "InsoCompat"=false "SkipID"=false "OIDC"=false "IgnoreSecurityErrors"=false}
2024/10/21 07:25:57 "level"=1 "msg"="tags after parsing x-kong-tags" "tags"=[]
2024/10/21 07:25:57 "level"=2 "msg"="no document name specified, trying x-kong-name"
2024/10/21 07:25:57 "level"=2 "msg"="no x-kong-name specified, trying Info.Title"
2024/10/21 07:25:57 "level"=1 "msg"="document name (namespace for UUID generation)" "name"="httpbin"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13a1d2c]

goroutine 1 [running]:
github.com/kong/go-apiops/openapi2kong.Convert({0xc0000ae000, 0x149, 0x200}, {{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x6b, 0xa7, ...}, ...})
	github.com/kong/go-apiops@v0.1.37/openapi2kong/openapi2kong.go:717 +0x134c
github.com/kong/deck/cmd.executeOpenapi2Kong(0xc0004d6f00?, {0xc0004fa2c0?, 0x4?, 0x17d8b83?})
	github.com/kong/deck/cmd/file_openapi2kong.go:61 +0x43e
github.com/spf13/cobra.(*Command).execute(0xc0004dfb08, {0xc0004fa280, 0x4, 0x4})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000a0008)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/kong/deck/cmd.Execute({0x1ab7230, 0xc000386cd0})
	github.com/kong/deck/cmd/root.go:266 +0x5f
main.main()
	github.com/kong/deck/main.go:31 +0x18
```
deck version is v1.40.2.
The OAS used for the test is as follows.
```yaml
openapi: 3.0.0
info:
  title: httpbin
  version: "0.2"
  /get:
    get:
      operationId: /get
      responses:
        "200":
          description: "get: response 200"
  /post:
    post:
      operationId: /post
      responses:
        "200":
          description: "post: response 200"
servers:
  - url: https://httpbin.org
```
The Dockerfile used for the test is as follows.
```dockerfile
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

# For Konnect API
RUN apt-get update
RUN apt-get install -y \
      curl \
      jq

# For deck CLI
RUN curl -sL https://github.com/kong/deck/releases/download/v1.40.2/deck_1.40.2_linux_amd64.tar.gz -o deck.tar.gz
RUN tar -xf deck.tar.gz -C /tmp
RUN install /tmp/deck /usr/local/bin/

# For inso CLI
RUN curl -sL https://github.com/Kong/insomnia/releases/download/core%4010.1.0/inso-linux-10.1.0.tar.xz -o inso.tar.xz
RUN apt-get install xz-utils
RUN tar -xf inso.tar.xz -C /tmp
RUN install /tmp/inso /usr/local/bin/

WORKDIR /root
CMD bash
```
When I ran the same command with this OAS file on Mac, it converted successfully without panics.
I'd be happy if anyone could give me advice.
Thank you.

**Comment by imurata** [comment]
Sorry, I missed inserting `paths`...
