### ISSUE TITLE
segfault encountered

### ISSUE THREAD

**Issue by Tieske** [Kong/deck#203]
Ran into the following error today, only once, could not reproduce after:

```
Thijss-MacBook:decK-examples thijs$ deck ping
Successfully connected to Kong!
Kong version:  1.5.0
Thijss-MacBook:decK-examples thijs$ cat config/kong.yaml
_format_version: "1.1"
_info:
  select_tags:
  - teamB
services:
- connect_timeout: 60000
  host: httpbin.org
  name: test
  path: /
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  tags:
  - serviceA
  - UnitX
Thijss-MacBook:decK-examples thijs$ deck diff -s config/
creating service test
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1527176]

goroutine 34 [running]:
github.com/kong/deck/cmd.sendAnalytics()
        /home/hbagdi/deck/cmd/analytics.go:41 +0x296
github.com/kong/deck/cmd.Execute.func1(0xc00012a000)
        /home/hbagdi/deck/cmd/root.go:55 +0x22
created by github.com/kong/deck/cmd.Execute
        /home/hbagdi/deck/cmd/root.go:54 +0x8e
Thijss-MacBook:decK-examples thijs$ deck diff -s config/
creating service test
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
Thijss-MacBook:decK-examples thijs$ deck diff -s config/
creating service test
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
Thijss-MacBook:decK-examples thijs$ deck diff -s config/
creating service test
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
Thijss-MacBook:decK-examples thijs$ deck diff -s config/
creating service test
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
Thijss-MacBook:decK-examples thijs$ deck -v
Error: unknown shorthand flag: 'v' in -v
Thijss-MacBook:decK-examples thijs$ deck version
decK v1.2.1 (59afa2a) 
Thijss-MacBook:decK-examples thijs$
```

Feel free to close if this does not provide enough info, as I am unable to reproduce (as seen from that snippet ^^^)

**Comment by hbagdi** [comment]
This is already fixed by #200.
