### ISSUE TITLE
nil pointer dereference on diff and sync

### ISSUE THREAD

**Issue by brendtumi** [Kong/deck#950]
Hello,

When running several different commands like diff or sync, I'm getting the following nil pointer dereference.

This is an example for a service giving this error:

```bash
> deck sync --kong-addr http://localhost:8001 -s kong-uat1-us.yaml

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ef82b]

goroutine 302 [running]:
github.com/kong/deck/types.(*routeDiffer).deleteDuplicateRoute(0x20?, 0xc002d96000)
	github.com/kong/deck/types/route.go:191 +0x2b
github.com/kong/deck/types.(*routeDiffer).DuplicatesDeletes(0xc0009ac360)
	github.com/kong/deck/types/route.go:178 +0x105
github.com/kong/deck/diff.(*Syncer).deleteDuplicates(0xc0026dab00)
	github.com/kong/deck/diff/diff.go:190 +0x50e
github.com/kong/deck/diff.(*Syncer).diff(0x0?)
	github.com/kong/deck/diff/diff.go:174 +0xa6
github.com/kong/deck/diff.(*Syncer).Run.func2()
	github.com/kong/deck/diff/diff.go:322 +0x2b
created by github.com/kong/deck/diff.(*Syncer).Run
	github.com/kong/deck/diff/diff.go:321 +0x31f
```

Kong: Version 2.8.0.0-enterprise-edition
Deck: decK v1.22.0 (7447a09)

There is a similar issue fixed https://github.com/Kong/deck/issues/944 but this is a new problem.

**Comment by blakefallow** [comment]
Kong Enterprise (free): v3.2.2 
Deck: v1.23

Hi @brendtumi 👋 We just ran into the same issue and were able to get past this by finding the consumers with a NULL username value and adding it:

psql:
`Select * from
(
select id, username, count(1)over(partition by username) as Cnt
from consumers
)a
Where Cnt > 1`

Hope this helps 🍻

**Comment by GGabriele** [comment]
Hi @brendtumi ,

This should be fixed in 1.22.1 and latest: https://github.com/Kong/deck/pull/945

Can you please upgrade decK and test again?

**Comment by brendtumi** [comment]
> Hi @brendtumi ,
> 
> This should be fixed in 1.22.1 and latest: #945
> 
> Can you please upgrade decK and test again?

Hi, issue is solved with 1.22.1
